### ISSUE TITLE
dhcpd doesn't sending NAK under certain conditions

### ISSUE THREAD

**Issue by kerel-fs** [kaleng/ansible-freifunk#4]
Requests innerhalb unseres subnet, aber ausserhalb des ip-ranges, den der entsprechende Supernode verteilt, werden nicht mit NAK beantwortet. Dies verzögert den Verbindungsaufbau in (seltenen) Fällen. Das Setzen von "authoritative" ist hier nicht ausreichend.

Lösung: "deny all clients" für den Range außerhalb des eigenen ip-ranges, siehe http://pastebin.com/7DCjaDPn .

Problem und Lösung von @RubenKelevra im IRC vorgestellt.

**Comment by RubenKelevra** [comment]
Dieses Problem tritt immer auf wenn ein anderes Gateway von dem Gerät vor der Verbindung verwendet wurde, entsprechend mit vielen Gateways tritt das Problem sehr häufig auf. 

Leider funktioniert der fix nicht für iOS, dort fragt ein Gerät drei mal die selbe IP ab, obwohl ein NAK gesendet wird. Daher wird der Verbindungsaufbau 5 mal so lang.

**Comment by kaleng** [comment]
fixed in [https://github.com/kaleng/freifunk.supernode/commit/26fac4b547d06b54e25f03eac127faac6c0b8045]
